== Klassenbeschreibung
=== Topic `+Stammdaten+`
Das Topic `+Stammdaten+` umfasst alle statischen Werte. Darunter fallen z.B. die Aufzählwerte von Listen (INTERLIS-Datentyp «Aufzählung»). Jede Liste wird in einer eigenen Klasse modelliert.

Die Stammdaten werden durch die zuständige Stelle vorgegeben. Bei Bundesthemen ist dies das für die Modellierung zuständige Bundesamt. Bei kantonalen Themen das zuständige kantonale Amt. Die Stammdaten von Bundesthemen können auf der Stufe Kanton erweiert werden. Die kantonalen Erweiterungen werden bei der Überführung ins Bundesmodell den entsprechenden Bundestypen zugeordnet.

Die Stammdaten werden durch die Abteilung Geoinformation nachgeführt und im Internet veröffentlicht.

==== Klasse `+Katalogeintrag+`
Die Klasse `+Katalogeintrag+` enthält die allgemeinen, für alle Kataloge gemeinsamen Attribute. Die Klasse selber ist abstrakt: Es gibt keine Objekte +Katalogeintrag+, sondern nur Objekte von den spezialisierten Klassen.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| Code
| Code des Listeneintrages; entspricht in INTERLIS dem Wert der Aufzählung und muss ein gültiger INTERLIS-Name sein (siehe https://www.interlis.ch/dokumentation[INTERLIS-Referenzhandbuch])
| in_Aenderung
| öffentlich
m| Name
| Bezeichnung des Katalogeintrages, wie er den Nutzenden angezeigt wird
| in Änderung
| öffentlich
m| SortierNr
| Reihenfolge des Katalogeintrages in der Auswahlliste
| 1
| öffentlich
m| Bemerkung
| Erläuterung, welche den Katalogeintrag näher beschreibt
| Dieser Status wird für alle Objekte verwendet, bei denen aktuell eine Nachführung läuft.
| öffentlich
|===

Die Katalogeinträge sind durch das Bundesamt vorgegeben und über die Datei http://models.geo.admin.ch/BAFU/Rodungen_Codetexte_V1_1.xml[Rodungen_Codetexte_V1_1.xml] publiziert. Diese Daten bilden die Grundlage für die Übernahme in die kantonalen Stammdaten. Es gilt folgende Zuorndung:

[cols=2*,options="header"]
|===
| Kanton | Bund
m| OID | wird einmalig vergeben
m| Code | entspricht dem Attribut `+Typ+` des XMLs bzw. dem Wert der Aufzählung im Modell
m| Name | deutscher Text gemäss XML (optimiert für GUI)
m| SortierNr | aufsteigende Zahl entsprechend der Reihenfolge im XML
m| Bemerkung | deutscher Text gemäss XML (unverändert!)
|===

==== Klasse `+Rodungstyp+`
Die Klasse `+Rodungstyp+` bezeichnet die Bedeutung der Rodungsgeometrie. Sie beinhaltet die Aufzählung "ObjektTyp" gemäss Bundesmodell.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Massnahme+`
Die Klasse `+Massnahme+` beinhaltet die Massnahmen, welche anstelle eines Realersatzes getroffen werden. Die Massnahmen werden zu Gunsten des Natur- und Landschaftsschutzes getroffen und entsprechen im Bundesmodell der Aufzählung `+MassnahmeNLTyp+`. Weil es nur Massnahmen zu Gunsten des Natur- und Landschaftsschutzes gibt, werden alle Massnahmen in die gleiche Klasse eingetragen und auf das Suffix "NL" (vgl. Bundesmodell) verzichtet.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Ersatzmassnahmeart+`
Die Klasse `+Ersatzmassnahmeart+` beinhaltet die Massnahmen, welche als Rodungsersatz getroffen werden. Die Ersatzmassnahmen entsprechen im Bundesmodell der Aufzählung `+ErsatzMassnahmenNL+`. Weil es nur Ersatzmassnahmen zu Gunsten des Natur- und Landschaftsschutzes gibt, werden alle Massnahmen in die gleiche Klasse eingetragen und auf das Suffix "NL" (vgl. Bundesmodell) verzichtet.

todo: Boolean mit abhängigem Wert; Boolean: "hat_Realersatz"

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Verzichtsgrund+`
Die Klasse `+Verzichtsgrund+` beinhaltet Gründe, weshalb auf einen Realersatz verzichtet wird. Die Werte entsprechen im Bundesmodell der Aufzählung `+ErsatzVerzicht+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

todo: Boolean mit abhängigem Wert; Boolean: "hat_Ersatzverzicht"

==== Klasse `+Zustaendigkeit+`
Die Klasse `+Zustaendigkeit+` beinhaltet die Staatsebene, welcher für die Rodung zuständig ist. Die Werte entsprechen im Bundesmodell der Aufzählung `+ZustaendigkeitsTyp+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Rodungszweck+`
Die Klasse `+Rodungszweck+` beinhaltet die Werte zum Rodungszweck und entsprecht im Bundesmodell der Aufzählung `+RodungszweckTyp+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Rodungsstand+`
Die Klasse `+Rodungsstand+` beinhaltet die Werte über den Stand der Rodung bzw. den Stand der Ersatzmassnahmen. Die Werte entsprecht im Bundesmodell der Aufzählung `+StandTyp+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Gemeinde+`
Die Klasse `+Gemeinde+` führte die schwyzer Gemeinden. Dieser Katalog ist eine kantonale Erweiterung.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

==== Klasse `+Genauigkeit+`
Die Klasse `+Genauigkeit+` führte Angaben über die Genauigkeit der Geometrien. Dieser Katalog ist eine kantonale Erweiterung.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
4+| _Diese Klasse führt keine zusätzlichen Attribute_
4+| *Anforderungen*
m|Code
3+| Die Werte müssen eindeutig sein
m|Name
3+| Die Werte müssen eindeutig sein
|===

todo: Werte in Masterkatalog erfassen:  (geometergenau, GPS-Einmessung, Daten vom Planer, digitalisiert mit Planscan, abgezeichnet, von AWN festgelgt)

=== Topic `+Fachdaten+`
Das Topic `+Fachdaten+` umfasst die eigentlichen, fachlichen Klassen des Themas.

==== Klasse `+Rodungsbewilligung+`
Die Klasse `+Rodungsbewilligung+` führt die Daten zur Rodungsbewilligung.

todo: Klaren, ob die fakultativen Attribute geführt werden müssen.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| erfasstVon
| Loginname der Person, welche den Datensatz erstellt hat (Autor); wird durch das System gesetzt
| Musterha
| +++<span style="color:red;">intern</span>+++
m| erfasstAm
| Datum und Zeit, an dem der Datensatz erstellt wurde; wird durch das System gesetzt
| 1980-03-21T15:38:12
| öffentlich
m| geaendertVon
| Loginname der Person, welche den Datensatz zuletzt geändert hat (Editor); wird durch das System gesetzt
| Muelleran
| +++<span style="color:red;">intern</span>+++
m| geaendertAm
| Datum und Zeit, an dem der Datensatz zuletzt geändert wurde; wird durch das System gesetzt
| 2024-07-30T08:07:57
| öffentlich
m| Kennung
| Kantonale Nummer, welche die Rodungsbewilligung eindeutig kennzeichnet.
| RO-08-01
| öffentlich
m| Kennung_Bund
| Nummer des Vorhabens, falls die Rodung nach Bundesverfahren läuft.
| SZ 2318-36
| öffentlich
m| Beschreibung
| Name oder Beschreibung des Vorhabens
| Erschliessung der Abbaukavernen
| öffentlich
m| hat_Realersatzpflicht
| Angabe, ob Realersatz zu leisten ist.
| ja
| öffentlich
m| Rodungsflaeche_def
| Fläche in m^2, die definitiv geordet wird
| 1234.00
| öffentlich
m| Rodungsflaeche_temp
| Fläche in m^2, die temporär geordet wird
| 4321.00
| öffentlich
m| Rodungsflaeche_histo
| Fläche in m^2 früherer Rodungen der letzten 15 Jahre
| 9876.00
| öffentlich
m| Realersatzflaeche
| Fläche in m^2 des Realersatzes
| 1212.00
| öffentlich
m| Verzichtsflaeche
| Fläche in m^2, für die auf Rodungsersatz verzichtet wird
| 50.00
| öffentlich
m| Massnahmeflaeche_total
| Gesamtfläche in m^2, auf der Massnahmen zu Gunsten des Natur- und Landschaftsschutzes zu leisten sind
| 850.00
| öffentlich
m| EA_Flaeche_total
| Gesamtfläche in m^2, auf der Ersatzaufforstung geleistet wird
| 125.00
| öffentlich
m| EA_Flaeche_gebietsfremd
| Gesamtfläche in m^2, auf der Ersatzaufforstung in einem anderen Gebiet geleistet wird
| 215.00
| öffentlich
m| Massnahmebeschreibung
| Beschreibung der Ersatzmassnamen zu Gunsten des Natur- und Landschaftsschutzes
| eine Beschreibung
| öffentlich
m| Massnahmeflaeche_Wald
| Fläche in m^2 der Natur- und Landschaftsschutzmassnahmen als Ersatz im Waldareal
| 60.00
| öffentlich
m| Massnahmeflaeche_Nichtwald
| Fläche in m^2 der Natur- und Landschaftsschutzmassnahmen als Ersatz ausserhalb des Waldareals
| 20.00
| öffentlich
m| hat_Massnahmenpool
| Angabe, ob die Ersatzmassnahmen im Rahmen eines Massnahmenpools realisiert werden
| ja
| öffentlich
m| Massnahmenbemerkung
| ergänzende Bemerkung zu den Ersatzmassnahmen
| eine Bemerkung
| öffentlich
m| Rodungszweckbemerkung
| ergänzende Bemerkung zum Rodungszweck
| eine Bemerkung
| öffentlich
m| Rodungsfrist
| Frist zur Benutzung der Rodungsbewilligung
| 2028-06-30
| öffentlich
m| Fristverlaengerung_RO
| Frist, bis zu welcher die Rodungsfrist verlängert wird
| 2028-12-31
| öffentlich
m| Rodungsfristbemerkung
| Bemerkung zur Rodungsfrist
| Die 90 Tage Rodungsfrist beginnen mit Rechtskraft der Rodungsbewilligung
| öffentlich
m| Ersatzfrist
| Frist zur Erfüllung der Ersatzmassnahmen
| 2029-12-31
| öffentlich
m| Ersatzfristbemerkung
| Bemerkung zur Ersatzfrist
| Die Ersatzfrist beginnt mit Rechtskraft der Rodungsbewilligung
| öffentlich
m| Fristverlaengerung_EA
| Frist, bis zu welcher die Ersatzaufforstungt verlängert wird
| 2031-12-31
| öffentlich
m| hat_Finanzausgleich
| finanzieller Ausgleich im Fall von erheblichen Vorteilen
| nein
| öffentlich
m| Abschlussdatum
| Datum, an dem das Vorhaben inkl. der Ersatzmassnahmen abgeschlossen ist
| 2025-04-15
| öffentlich
m| Verfuegungsdatum
| Datum der Verfügung
| 2015-03-03
| öffentlich
m| Referenz
| Andere Rodungsvorhaben, die mit diesem Dossier verbunden sind, sowie weitere Referenzen
| RO-99-75, RO-99-76, RO-99-77
| öffentlich
m| Erfassungsdatum_GIS
| Datum, an dem die Rodungsgeometrie erfasst wurde
| 2018-02-19
| öffentlich
m| Baugesuchsnummer
| Referenz zum Baugesuch
| PB-22-005
| öffentlich
m| Bemerkung_intern
| interne Bemerkung
| Das ist eine interne Bemerkung.
| +++<span style="color:red;">intern</span>+++
m| Bemerkung
| Bemerkung
| Das ist eine Bemerkung.
| öffentlich
4+| *Beziehungsattribute*
m| rErsatzmassnahmeart
| Fremdschlüssel zur Ersatzmassnahmeart (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rVerzichtsgrund
| Fremdschlüssel zum Verzichtsgrund (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rZustaendigkeit
| Fremdschlüssel zur Zustaendigkeit (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rMassnahme
| Fremdschlüssel zur Massnahme (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rRodungszweck
| Fremdschlüssel zum Rodungszweck (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rRodungsstand
| Fremdschlüssel zum Rodungsstand (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rGemeinde
| Fremdschlüssel zur Gemeinde (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
4+| *Geometrie*
4+| - - -
4+| *Bedingungen*
m|Kennung
3+a| * Die Werte müssen innerhalb der Klasse eindeutig sein.
* Nach der Vergabe muss der Wert unverändert bleiben.
m|rGemeinde
3+a| * Die erste Gemeinde ist die führende. Ihr soll das Beziehungsattribut `+ist_fuehrend+` auf TRUE gesetzt werden; bei den anderen auf FALSE.
|===

==== Klasse `+Geometrie+`
Die Klasse `+Geometrie+` enthält die allgemeinen, für alle geometrischen Klassen gemeinsamen Attribute. Die Klasse selber ist abstrakt: Es gibt keine Objekte +Geometrieg+, sondern nur Objekte von den spezialisierten Klassen.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| OID
| technischer Objektidentifikator
| ceaa37a9-8614-43fc-9a8b-688f95c30218
| öffentlich
m| erfasstVon
| Loginname der Person, welche den Datensatz erstellt hat (Autor); wird durch das System gesetzt
| Musterha
| +++<span style="color:red;">intern</span>+++
m| erfasstAm
| Datum und Zeit, an dem der Datensatz erstellt wurde; wird durch das System gesetzt
| 1980-03-21T15:38:12
| öffentlich
m| geaendertVon
| Loginname der Person, welche den Datensatz zuletzt geändert hat (Editor); wird durch das System gesetzt
| Muelleran
| +++<span style="color:red;">intern</span>+++
m| geaendertAm
| Datum und Zeit, an dem der Datensatz zuletzt geändert wurde; wird durch das System gesetzt
| 2024-07-30T08:07:57
| öffentlich
m| Massnahmebeschreibung
| Beschreibung der Ersatzmassnahme zu Gunsten des Natur- und Landschaftsschutzes
| Renaturierung alter Steinbruch
| öffentlich
m| Bemerkung
| Bemerkung
| Das ist eine Bemerkung.
| öffentlich
4+| *Beziehungsattribute*
m| rRodungstyp
| Fremdschlüssel zum Rodungstyp (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rMassnahme
| Fremdschlüssel zur Massnahme (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rGenauigkeit
| Fremdschlüssel zur Genauigkeit (Stammdaten)
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
m| rRodungsbewilligung
| Fremdschlüssel zur Rodungsbewilligung, zu welcher die Geometrie zugeordnet ist
| ccee2bad-419e-454e-9e0f-9ef2ae2d4d44
| öffentlich
|===

==== Klasse `+Lage+`
Die Klasse `+Lage+` führt die Geometrie als Punkt. Sie ist eine Spezialisierung der Klasse `+Geometrie+`. Der Punktgeometrie hat eine Doppelfunktion. Sie kann:

* entweder das Gebiet der Rodungs- oder Ersatzfläche als Punkt kennzeichnen
* oder als Schwerpunkt des Vorhabens dienen.

Im ersten Fall wird `+ist_Schwerpunkt+` FALSE, im zweiten Fall TRUE gesetzt.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| ist_Schwerpunkt
| Gibt an, ob die Punktegeometrie als Schwerpunkt oder als verallgemeinerter Rodungsort dient.
| FALSE
| öffentlich
m| Geometrie
| Geometrie des Objektes als Punkt
| (ohne Beispiel)
| öffentlich
4+| *Bedingungen*
m|ist_Schwerpunkt
3+a| * Falls TRUE, dann muss der Punkt innerhalb der grössten Teilfäche des Vorhabens liegen.
|===

==== Klasse `+Flaeche+`
Die Klasse `+Flaeche+` führt die Geometrie als Einzelfläche. Sie ist eine Spezialisierung der Klasse `+Geometrie+`.

[cols=4*,options="header"]
|===
| Name | Beschreibung | Beispiel | Freigabe
m| Geometrie
| Geometrie des Objektes als Einzelfläche
| (ohne Beispiel)
| öffentlich
|===

ifdef::backend-pdf[]
<<<
endif::[]
