== Modellbeschreibung

Das Bundesgesetz über den Wald (Waldgesetz, WaG) <<allgemeines.adoc#doc-05,[5]>> bezweckt die Erhaltung der Waldfläche in der Schweiz bezüglich Ausdehnung und Qualität (Art. 1 WaG). Deshalb sind Rodungen gemäss Bundesgesetz über den Wald grundsätzlich verboten (Art. 5 Abs. 1 WaG). Unter bestimmten Voraussetzungen dürfen Ausnahmebewilligungen erteilt werden. Für jede Rodung muss der Gesuchsteller nachweisen können, dass wichtige Gründe das öffentliche Interesse an der Walderhaltung überwiegen sowie weitere Voraussetzungen erfüllen (Art. 5 WaG).

Ein Rodungsgesuch wird in der Regel im Rahmen eines Baugesuchs eingereicht. Die Ausnahmebewilligung für die Rodung wird je nach Leitverfahren durch den Kanton oder den Bund erteilt (Art. 6 WaG). Temporäre Rodungen werden nach Projektende vollumfänglich wiederhergestellt; die Zweckentfremdung des Waldbodens ist in diesem Fall vorübergehend und hat keine Veränderung der Waldfläche zur Folge. Jede definitive Rodung ist durch eine mindestens gleich grosse, neu zu begründende Waldfläche in gleicher Gegend zu ersetzen (Ersatzaufforstungsfläche = Realersatz). In bestimmten Fällen können auch Massnahmen zu Gunsten des Natur- und Landschaftsschutzes als Ersatz anerkannt werden, oder es kann unter Umständen sogar ganz auf den Realersatz verzichtet werden (Art. 7 WaG).

Die Geodaten der Rodungen und des Rodungsersatzes gehören zu den Geobasisdaten des Bundesrechts (Anhang 1 GeoIV) <<allgemeines.adoc#doc-02,[2]>>. Kantone müssen zur Übersicht und Kontrolle einen Geodatensatz aller bewilligten Rodungs- und Ersatzaufforstungsflächen führen und in geeigneter Form und Qualität der Öffentlichkeit zur Verfügung stellen (Art. 1 GeoIG) <<allgemeines.adoc#doc-01,[1]>>. Dazu gibt der Bund ein minimales Geodatenmodell vor, welches die Kantone mit zusätzlichen Attributen erweitern können.

Das Amt für Wald und Natur des Kantons Schwyz führt seine Geodaten der Rodungen und des Rodungsersatzes gemäss dem vorliegenden Geodatenmodell.


ifdef::backend-pdf[]
<<<
endif::[]
